---
- name: 中文测试手册
  hosts: all
  sources:
    - name: my test source
      ansible.eda.range:
        limit: "{{ my_limit }}"
  rules:
    - name: 运行中文工作模版
      condition: event.i > 1
      action:
        print_event:
