---
- name: 中文测试手册
  hosts: all
  sources:
    - name: my test source
      ansible.eda.range:
        limit: 6
  rules:
    - name: 运行中文工作模版
      condition: event.i == 1
      action:
        run_job_template:
          name: 中文任务测试
          organization: Default
          job_args:
            extra_vars:
              hello: Fred
