---
- name: Test run job templates
  hosts: all
  sources:
    - name: my test source
      ansible.eda.range:
        limit: 10
        delay: 20
  rules:
    - name: Run job template
      condition: event.i > 1
      actions:
        - run_job_template:
            name: Demo Job Template
            organization: Default
            job_args:
              extra_vars:
                hello: Fred
        - debug:
            msg:
              - debug message 1
              - debug message 2
        - print_event:
            pretty: true
