- name: Test dynamic changing credentials
  hosts: all
  sources:
    - name: my test source
      ansible.eda.generic:
        payload: 
           - msg: "fail"
           - i : 10
        loop_count: 30
        loop_delay: 1
  rules:
    - name: shutdown
      condition: event.msg == vars.current_mesg
      actions:
        - shutdown:
            delay: 0.125
            message: Shutting down because of fail set
    - name: validate i
      condition: event.i > 0
      actions:
        - debug:
            msg: Simple debug message
        - print_event:
