---
- name: set1
  hosts: all
  sources:
    - name: sourceA
      ansible.eda.range:
        limit: 6
        delay: 10
  rules:
    - name: rule1
      condition: event.i == 1
      actions:
        - run_job_template:
            name: Hello, World
            organization: Default
            job_args:
              extra_vars:
                hello: Adam
        - run_job_template:
            name: Hello World
            organization: Default
            job_args:
              extra_vars:
                hello: Fred
        - debug:
            msg:
              - debug message 1
              - debug message 2
        - print_event:
            pretty: true
