---
- name: Test multiple actions and events
  hosts: all
  sources:
    - name: my test source
      ansible.eda.range:
        limit: 10
  rules:
    - name: rule with 3 actions
      condition: event.i == 1
      actions:
        - run_job_template:
            name: Demo Job Template
            organization: Default
            job_args:
              extra_vars:
                hello: Fred
        - debug:
            msg:
              - debug message 1
              - debug message 2
        - print_event:
            pretty: true
    - name: rule with 2 events
      condition:
        all: 
          - event.i == 3
          - event.i == 7
      action:
        print_event:
          pretty: true
    - name: rule with 1 action
      condition: event.i == 2
      action:
        debug:
