---
- name: set1
  hosts: all
  sources:
    - name: sourceA
      ansible.eda.range:
        limit: 6
        delay: 10
  rules:
    - name: rule1
      condition: event.i == 1
      action:
        print_events:
    - name: rule2
      condition: event.i == 2
      action:
        debug:
