---
- name: set1
  hosts: all
  sources:
    - name: sourceA
      ansible.eda.range:
        limit: 100
  rules:
    - name: rule1
      condition: event.i < 101
      action:
        run_job_template:
          name: Hello World
          organization: Default
          job_args:
            extra_vars:
              hello: Fred
