---
- name: Listen for storage-monitor events
  hosts: all
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5555
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 4444

  rules:
    - name: webhook event
      condition: "true == true"
      action:
        print_event:
