---
- name: Test run workflow templates
  hosts: all
  sources:
    - ansible.eda.range:
        limit: 5
  rules:
    - name: "Run workflow template"
      condition: event.i == 1
      action:
        run_workflow_template:
          name: "{{ WORKFLOW_TEMPLATE_NAME }}"
          job_args:
            extra_vars:
              hello: Fred
          retries: 1
          delay: 10
          set_facts: True
          organization: Default
