---
- name: set1
  hosts: all
  sources:
    - name: sourceA
      ansible.eda.range:
        limit: 6
        delay: 15
  rules:
    - name: rule1
      condition: event.i == 1
      action:
        run_job_template:
          name: Hello World
          organization: Default
          job_args:
            extra_vars:
              hello: Fred
    - name: rule2
      condition: event.i == 2
      action:
        debug:
    - name: rule3
      condition: event.i > 3
      action:
        run_job_template:
          name: Hello World
          organization: Default
          job_args:
            extra_vars:
              hello: Fred
