---
- name: Test run job templates
  hosts: all
  sources:
    - ansible.eda.range:
        limit: 6
  rules:
    - name: Run job template
      condition: event.i == 1
      action:
        run_job_template:
          name: Hello World
          organization: Default
          job_args:
            extra_vars:
              hello: Fred
          retries: 1
          delay: 10
    - name: Debug
      condition: event.i == 2
      action:
        debug:
    - name: print_event
      condition: event.i == 3
      action:
        print_event:
          pretty: true
    - name: set_fact
      condition: event.i == 4
      action:
        set_fact:
          fact:
            name: fred
